apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rbln-npu-operator.fullname" . }}-metrics-auth
  labels:
    {{- include "rbln-npu-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics-auth
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
