---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "rbln-npu-operator.labels" . | nindent 4 }}
  name: {{ include "rbln-npu-operator.fullname" . }}
rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    - nodes
    - pods
    - serviceaccounts
    - services
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - apps
    resources:
    - daemonsets
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - config.openshift.io
    resources:
    - clusterversions
    - proxies
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - clusterrolebindings
    - clusterroles
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - rolebindings
    - roles
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - rebellions.ai
    resources:
    - rblnclusterpolicies
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - rebellions.ai
    resources:
    - rblndrivers
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - rebellions.ai
    resources:
    - rblndrivers/finalizers
    verbs:
    - update
  - apiGroups:
    - rebellions.ai
    resources:
    - rblndrivers/status
    verbs:
    - get
    - patch
    - update
  - apiGroups:
    - rebellions.ai
    resources:
    - rblnclusterpolicies/finalizers
    verbs:
    - update
  - apiGroups:
    - rebellions.ai
    resources:
    - rblnclusterpolicies/status
    verbs:
    - get
    - patch
    - update
  - apiGroups:
    - security.openshift.io
    resources:
    - securitycontextconstraints
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - security.openshift.io
    resourceNames:
    - privileged
    resources:
    - securitycontextconstraints
    verbs:
    - use
