apiVersion: rebellions.ai/v1beta1
kind: RBLNClusterPolicy
metadata:
  labels:
    {{- include "rbln-npu-operator.labels" . | nindent 4 }}
  name: rbln-cluster-policy
spec:
  name: {{ .Values.name }}
  {{- if .Values.daemonsets }}
  daemonsets:
    {{- with .Values.daemonsets.labels }}
    labels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.daemonsets.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.daemonsets.affinity }}
    affinity:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.daemonsets.tolerations }}
    tolerations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if .Values.daemonsets.priorityClassName }}
    priorityClassName: {{ .Values.daemonsets.priorityClassName | quote }}
    {{- end }}
  {{- end }}
  devicePlugin:
    enabled: {{ .Values.devicePlugin.enabled }}
    registry: {{ .Values.devicePlugin.image.registry }}
    image: {{ .Values.devicePlugin.image.repository }}
    version: {{ .Values.devicePlugin.image.tag | quote }}
    imagePullPolicy: {{ .Values.devicePlugin.image.pullPolicy }}
    hostBinPath: {{ .Values.devicePlugin.hostBinPath | quote }}
    {{- if .Values.devicePlugin.resourceList }}
    resourceList:
      {{- toYaml .Values.devicePlugin.resourceList | nindent 4 }}
    {{- end }}

  draKubeletPlugin:
    enabled: {{ .Values.draKubeletPlugin.enabled }}
    registry: {{ .Values.draKubeletPlugin.image.registry }}
    image: {{ .Values.draKubeletPlugin.image.repository }}
    version: {{ .Values.draKubeletPlugin.image.tag | quote }}
    imagePullPolicy: {{ .Values.draKubeletPlugin.image.pullPolicy }}
    priorityClassName: {{ .Values.draKubeletPlugin.priorityClassName | quote }}
    driverName: {{ .Values.draKubeletPlugin.driverName | quote }}
    kubeletRegistrarDirectoryPath: {{ .Values.draKubeletPlugin.kubeletRegistrarDirectoryPath | quote }}
    kubeletPluginsDirectoryPath: {{ .Values.draKubeletPlugin.kubeletPluginsDirectoryPath | quote }}
    healthcheckPort: {{ .Values.draKubeletPlugin.healthcheckPort }}

  metricsExporter:
    enabled: {{ .Values.metricsExporter.enabled }}
    registry: {{ .Values.metricsExporter.image.registry }}
    image: {{ .Values.metricsExporter.image.repository }}
    imagePullPolicy: {{ .Values.metricsExporter.image.pullPolicy }}
    version: {{ .Values.metricsExporter.image.tag | quote }}

  rblnDaemon:
    enabled: {{ .Values.rblnDaemon.enabled }}
    registry: {{ .Values.rblnDaemon.image.registry }}
    image: {{ .Values.rblnDaemon.image.repository }}
    imagePullPolicy: {{ .Values.rblnDaemon.image.pullPolicy }}
    version: {{ .Values.rblnDaemon.image.tag | quote }}
    hostPort: {{ .Values.rblnDaemon.hostPort }}
    {{- if .Values.rblnDaemon.imagePullSecrets }}
    imagePullSecrets:
      {{- toYaml .Values.rblnDaemon.imagePullSecrets | nindent 6 }}
    {{- end }}
    {{- if .Values.rblnDaemon.resources }}
    resources:
      {{- toYaml .Values.rblnDaemon.resources | nindent 6 }}
    {{- end }}
    {{- if .Values.rblnDaemon.args }}
    args:
      {{- toYaml .Values.rblnDaemon.args | nindent 6 }}
    {{- end }}
    {{- if .Values.rblnDaemon.env }}
    env:
      {{- toYaml .Values.rblnDaemon.env | nindent 6 }}
    {{- end }}

  npuFeatureDiscovery:
    enabled: {{ .Values.npuFeatureDiscovery.enabled }}
    registry: {{ .Values.npuFeatureDiscovery.image.registry }}
    image: {{ .Values.npuFeatureDiscovery.image.repository }}
    imagePullPolicy: {{ .Values.npuFeatureDiscovery.image.pullPolicy }}
    version: {{ .Values.npuFeatureDiscovery.image.tag | quote }}

  containerToolkit:
    enabled: {{ .Values.containerToolkit.enabled }}
    registry: {{ .Values.containerToolkit.image.registry }}
    image: {{ .Values.containerToolkit.image.repository }}
    imagePullPolicy: {{ .Values.containerToolkit.image.pullPolicy }}
    version: {{ .Values.containerToolkit.image.tag | quote }}
    {{- if .Values.containerToolkit.imagePullSecrets }}
    imagePullSecrets:
      {{- toYaml .Values.containerToolkit.imagePullSecrets | nindent 6 }}
    {{- end }}
    {{- if .Values.containerToolkit.resources }}
    resources:
      {{- toYaml .Values.containerToolkit.resources | nindent 6 }}
    {{- end }}
    {{- if .Values.containerToolkit.args }}
    args:
      {{- toYaml .Values.containerToolkit.args | nindent 6 }}
    {{- end }}
    {{- if .Values.containerToolkit.env }}
    env:
      {{- toYaml .Values.containerToolkit.env | nindent 6 }}
    {{- end }}

  sandboxDevicePlugin:
    enabled: {{ .Values.sandboxDevicePlugin.enabled }}
    registry: {{ .Values.sandboxDevicePlugin.image.registry }}
    image: {{ .Values.sandboxDevicePlugin.image.repository }}
    imagePullPolicy: {{ .Values.sandboxDevicePlugin.image.pullPolicy }}
    version: {{ .Values.sandboxDevicePlugin.image.tag | quote }}
    {{- if .Values.sandboxDevicePlugin.resourceList }}
    resourceList:
      {{- toYaml .Values.sandboxDevicePlugin.resourceList | nindent 4 }}
    {{- end }}
    vfioChecker:
      registry: {{ .Values.sandboxDevicePlugin.vfioChecker.image.registry }}
      image: {{ .Values.sandboxDevicePlugin.vfioChecker.image.repository }}
      version: {{ .Values.sandboxDevicePlugin.vfioChecker.image.tag | quote }}

  vfioManager:
    enabled: {{ .Values.vfioManager.enabled }}
    registry: {{ .Values.vfioManager.image.registry }}
    image: {{ .Values.vfioManager.image.repository }}
    imagePullPolicy: {{ .Values.vfioManager.image.pullPolicy }}
    version: {{ .Values.vfioManager.image.tag | quote }}

  validator:
    registry: {{ .Values.validator.image.registry }}
    image: {{ .Values.validator.image.repository }}
    imagePullPolicy: {{ .Values.validator.image.pullPolicy }}
    version: {{ .Values.validator.image.tag | quote }}
    {{- if .Values.validator.imagePullSecrets }}
    imagePullSecrets:
      {{- toYaml .Values.validator.imagePullSecrets | nindent 6 }}
    {{- end }}
    {{- if .Values.validator.resources }}
    resources:
      {{- toYaml .Values.validator.resources | nindent 6 }}
    {{- end }}
    {{- if .Values.validator.args }}
    args:
      {{- toYaml .Values.validator.args | nindent 6 }}
    {{- end }}
    {{- if .Values.validator.env }}
    env:
      {{- toYaml .Values.validator.env | nindent 6 }}
    {{- end }}
    plugin:
      {{- if .Values.validator.plugin.env }}
      env:
        {{- toYaml .Values.validator.plugin.env | nindent 8 }}
      {{- end }}
    toolkit:
      {{- if .Values.validator.toolkit.env }}
      env:
        {{- toYaml .Values.validator.toolkit.env | nindent 8 }}
      {{- end }}
    driver:
      {{- if .Values.validator.driver.env }}
      env:
        {{- toYaml .Values.validator.driver.env | nindent 8 }}
      {{- end }}
    vfioPCI:
      {{- if .Values.validator.vfioPCI.env }}
      env:
        {{- toYaml .Values.validator.vfioPCI.env | nindent 8 }}
      {{- end }}
